# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tom/Documents/projects/perfect-hash-table

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tom/Documents/projects/perfect-hash-table

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tom/Documents/projects/perfect-hash-table/CMakeFiles /Users/tom/Documents/projects/perfect-hash-table//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tom/Documents/projects/perfect-hash-table/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pht

# Build rule for target.
pht: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pht
.PHONY : pht

# fast build rule for target.
pht/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/build
.PHONY : pht/fast

# target to build an object file
src/phs.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/phs.o
.PHONY : src/phs.o

# target to preprocess a source file
src/phs.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/phs.i
.PHONY : src/phs.i

# target to generate assembly for a file
src/phs.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/phs.s
.PHONY : src/phs.s

# target to build an object file
src/pht.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/pht.o
.PHONY : src/pht.o

# target to preprocess a source file
src/pht.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/pht.i
.PHONY : src/pht.i

# target to generate assembly for a file
src/pht.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/pht.s
.PHONY : src/pht.s

# target to build an object file
src/phtfnv.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/phtfnv.o
.PHONY : src/phtfnv.o

# target to preprocess a source file
src/phtfnv.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/phtfnv.i
.PHONY : src/phtfnv.i

# target to generate assembly for a file
src/phtfnv.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pht.dir/build.make CMakeFiles/pht.dir/src/phtfnv.s
.PHONY : src/phtfnv.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... pht"
	@echo "... src/phs.o"
	@echo "... src/phs.i"
	@echo "... src/phs.s"
	@echo "... src/pht.o"
	@echo "... src/pht.i"
	@echo "... src/pht.s"
	@echo "... src/phtfnv.o"
	@echo "... src/phtfnv.i"
	@echo "... src/phtfnv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

